version: '3'
services:
  magento:
    build:
      context: .
      dockerfile: magento/Dockerfile
      args:
        PHP_VERSION: 8.1
        MAGENTO_VERSION: 2.4.4
    networks:
      - appnet
    command: /opt/magento2/start_magento.sh
    depends_on:
      - db
      - elasticsearch
    expose:
      - 80
    env_file:
      - .env

  nginx:
    build:
      context: .
      dockerfile: nginx-front/Dockerfile
    ports:
      - 80:80
    networks:
      - appnet
    command: /etc/wait-for-it.sh magento:80 -t 300 -- nginx -g 'daemon off;'

  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env
    networks:
      - appnet
    expose:
      - 3306

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    container_name: elasticsearch
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 262144
        hard: 262144
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    networks:
      - appnet


volumes:
  db_data:
    driver: "local"

networks:
  appnet: